version: '2'
services:
  discord-soundbot:
    build: .
    image: soundbot
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ./sounds:/app/sounds
      - ./config/config.json:/app/config/config.json
      - ./db.json:/app/db.json
